name: build
on:
  workflow_dispatch:
  push:
jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Compile document in LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Rename document
        run: mv main.pdf buku-ta.pdf

      - name: Upload document as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: buku-ta.pdf
